# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Mac
  pool:
    name: 'AvaloniaMacPool'

  steps:
  - script: ./tests/Avalonia.IntegrationTests.Appium/macos-clean-build-test.sh
    displayName: 'run integration tests'


- job: Windows
  pool:
    vmImage: 'windows-2022'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 6.0.202'
    inputs:
      version: 6.0.202
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'samples/IntegrationTestApp/IntegrationTestApp.csproj'

  - task: CmdLine@2
    displayName: 'install appium'
    inputs:
      script: |
        npm install -g appium@next
        appium driver install windows
  
  - task: PowerShell@2
    displayName: 'run appium server'
    inputs:
      targetType: 'inline'
      script: |
        appium

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'tests/Avalonia.IntegrationTests.Appium/Avalonia.IntegrationTests.Appium.csproj'
