# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Mac
  pool:
    name: 'AvaloniaMacPool'

  steps:
  - script: |
      pkill node
      appium &
      pkill IntegrationTestApp
      ./build.sh CompileNative
      ./samples/IntegrationTestApp/bundle.sh
      open -n ./samples/IntegrationTestApp/bin/Debug/net6.0/osx-arm64/publish/IntegrationTestApp.app
      pkill IntegrationTestApp

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'tests/Avalonia.IntegrationTests.Appium/Avalonia.IntegrationTests.Appium.csproj'

  - script: |
      pkill IntegrationTestApp
      pkill node


- job: Windows
  pool:
    vmImage: 'windows-2022'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 6.0.202'
    inputs:
      version: 6.0.202
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'samples/IntegrationTestApp/IntegrationTestApp.csproj'

  - script: npm install --location=global appium@next --unsafe-perm=true --allow-root
  - script: appium driver install windows
    
  - task: PowerShell@2
    displayName: 'run appium server'
    inputs:
      targetType: 'inline'
      script: |
        Start-Job -Command {appium}aaaaaaa
        dotnet test tests/Avalonia.IntegrationTests.Appium


