# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Mac
  pool:
    name: 'AvaloniaMacPool'

  steps:
  - script: ./tests/Avalonia.IntegrationTests.Appium/macos-clean-build-test.sh
    displayName: 'run integration tests'


- job: Windows
  pool:
    vmImage: 'windows-2022'

  steps:
    script: |
    npm --version
    npm config get prefix
    dir c:\\npm\\prefix
    npm install -g appium@next
    c:\\npm\\prefix\\appium.cmd driver install windows
    c:\\npm\\prefix\\appium.cmd
    
  - task: PowerShell@2
    displayName: 'run appium server'
    inputs:
      targetType: 'inline'
      script: |
        dotnet test tests/Avalonia.IntegrationTests.Appium


