jobs:
- job: Windows
  pool:
    vmImage: 'windows-2022'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 6.0 Runtime'
    inputs:
      packageType: runtime
      version: 6.0.x

  - task: UseDotNet@2
    displayName: 'Use .NET 8.0 SDK'
    inputs:
      packageType: sdk
      useGlobalJson: true

  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Start'
      AgentResolution: '4K'
    displayName: 'Start WinAppDriver'
  
  - task: DotNetCoreCLI@2
    displayName: 'Build IntegrationTestApp'
    inputs:
      command: 'build'
      projects: 'samples/IntegrationTestApp/IntegrationTestApp.csproj'
  
  - task: DotNetCoreCLI@2
    displayName: 'Build test project'
    inputs:
      command: 'build'
      projects: 'tests\Avalonia.IntegrationTests.Appium\Avalonia.IntegrationTests.Appium.csproj'

  - task: VSTest@2
    displayName: 'Run Integration Tests'
    inputs:
      testAssemblyVer2: '**/Avalonia.IntegrationTests.Appium.dll'
      runSettingsFile: 'tests\Avalonia.IntegrationTests.Appium\ci.runsettings'

  - publish: D:\a\_temp\TestResults
    displayName: 'Publish test results'
    condition: failed()

  - task: Windows Application Driver@0
    inputs:
      OperationType: 'Stop'
    displayName: 'Stop WinAppDriver'
