# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Mac
  pool:
    name: 'AvaloniaMacPool'

  steps:
  - script: ./tests/Avalonia.IntegrationTests.Appium/macos-clean-build-test.sh
    displayName: 'run integration tests'


- job: Windows
  pool:
    vmImage: 'windows-2022'

  steps:
  - task: CmdLine@2
    displayName: 'install appium'
    inputs:
      script: |
        npm --version
        npm install -g appium@next
        C:/npm/prefix/appium driver install windows
  
  - task: PowerShell@2
    displayName: 'run appium server'
    inputs:
      targetType: 'inline'
      script: |
        C:/npm/prefix/appium
        dotnet test tests/Avalonia.IntegrationTests.Appium


